version: 2.1
description: CircleCI orb for NowSecure AUTO that provides fully automated, mobile
  appsec testing coverage
executors:
  default:
    description: Java docker container to use when running the NowSecure AUTO orb
    docker:
    - image: circleci/openjdk:8-jdk-node
    environment:
      TERM: dumb
commands:
  sectest:
    description: Executes security test using NowSecure AUTO.
    parameters:
      # url for nowsecure auto API
      auto_url:
        type: string
        default: https://lab-api.nowsecure.com
      # API token, visit https://docs.nowsecure.com/auto/integration-services/jenkins-integration to generate token
      auto_token:
        type: string
        default: $AUTO_TOKEN
      # Specify group if you belong to multiple groups
      auto_group:
        type: string
        default: $AUTO_GROUP
      # Specify artifacts-dir where security artifacts will be stored
      auto_dir:
        type: string
        default: "/tmp/workspace/nowsecure-auto-security-test"
      # Specify absolute path of mobile binary, you would need to attach workspace to this plugin step
      auto_file:
        type: string
      # Specify maximum time to wait for results, if you specify 0 then plugin won't wait for the results
      auto_wait:
        type: string
        default: "30"
      # Specify minimum score the app should get from security testing, if you specify 0 then score won't be evaulated otherwise build will be marked as failure if security score is below this number
      auto_score:
        type: string
        default: "50"
    steps:
    - attach_workspace:
        at: /tmp/workspace
    - run: curl -Ls https://github.com/bhatti/circle-auto/archive/0.3.tar.gz | tar -xzf - -C .
    - run: cd circle-auto-0.3 && gradle run -Dauto.url=<< parameters.auto_url >> -Dauto.token=<< parameters.auto_token >> -Dauto.dir=<< parameters.auto_dir >> -Dauto.file=<< parameters.auto_file >> -Dauto.group=<< parameters.auto_group >> -Dauto.wait=<< parameters.auto_wait >> -Dauto.score=<< parameters.auto_score >>
    - persist_to_workspace:
        root: /tmp/workspace
        paths:
        - nowsecure-auto-security-test/*
    - store_artifacts:
        path: /tmp/workspace/nowsecure-auto-security-test
        destination: nowsecure-auto-security-test
