version: 2.1
orbs:
  insectest:
    jobs:
      inline_job:
        parameters:
          auto_url:
            type: string
            default: "https://lab-api.nowsecure.com"
          auto_token:
            type: string
            default: $AUTO_TOKEN
          auto_group:
            type: string
            default: $AUTO_GROUP
          auto_file:
            type: string
            default: $AUTO_FILE
          auto_wait:
            type: string
            default: "30"
          auto_score:
            type: string
            default: "50"
        executor: inline_executor
        steps:
          - inline_command:
              auto_url: <<parameters.auto_url>>
              auto_token: <<parameters.auto_token>>
              auto_group: <<parameters.auto_group>>
              auto_file: <<parameters.auto_file>>
              auto_wait: <<parameters.auto_wait>>
              auto_score: <<parameters.auto_score>>
    commands:
      inline_command:
        parameters:
          auto_url:
            type: string
            default: "https://lab-api.nowsecure.com"
          auto_token:
            type: string
            default: $AUTO_TOKEN
          auto_group:
            type: string
            default: $AUTO_GROUP
          auto_file:
            type: string
            default: $AUTO_FILE
          auto_wait:
            type: string
            default: "30"
          auto_score:
            type: string
            default: "50"
        steps:
          - attach_workspace:
              at: /tmp/workspace
          - run: mkdir -p /tmp/workspace/nowsecure-auto-security-test
          - run: cp apkpure_app_887.apk /tmp/workspace/test.apk
          - checkout
          - run: gradle run -Dauto.url=<< parameters.auto_url >> -Dauto.token=<< parameters.auto_token >> -Dauto.file=<< parameters.auto_file >> -Dauto.group=<< parameters.auto_group >> -Dauto.wait=<< parameters.auto_wait >> -Dauto.score=<< parameters.auto_score >>
          - persist_to_workspace:
              root: /tmp/workspace
              paths:
                - nowsecure-auto-security-test/*
    executors:
      inline_executor:
        docker:
          - image: circleci/openjdk:8-jdk-node
        environment:
          TERM: dumb
workflows:
  test:
    jobs:
      - insectest/inline_job:
        auto_file: test.apk
