version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
    - checkout
  test:
    docker:
    - image: circleci/openjdk:8-jdk
    environment:
    - TERM: dumb
    steps:
    - run:
        command: "echo file $AUTO_FILE dir $AUTO_DIR cir $CIRCLE_WORKING_DIRECTORY"
workflows:
  version: 2
  workflow:
    jobs:
    - build
    - test
