version: 2.1
jobs: # a job that invokes the `security test
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      - TERM: dumb
    parameters:
      auto_url:
        type: string
        default: "https://lab-api.nowsecure.com"
      auto_token:
        type: string
        default: ${AUTO_TOKEN}
    steps:
      - checkout
      - run: gradle run -Dauto.url=parameters.auto_url -Dauto.token=parameters.auto_token -Dauto.file=${AUTO_FILE} -Dauto.dir=${AUTO_DIR} -Dauto.group=${AUTO_GROUP} -Dauto.wait=${AUTO_WAIT} -Dauto.score=${AUTO_SCORE}
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test
