version: 2.1
orbs:
  circle-auto-v1:
    executors:
      default:
        docker:
          - image: circleci/openjdk:8-jdk-node
        environment:
          # Disable fancy terminal updates
          TERM: dumb
    jobs:
      security-test:
        executor: default
        parameters:
          auto_url:
            type: string
            default: "https://lab-api.nowsecure.com"
          auto_token:
            type: string
            default: ${AUTO_TOKEN}
        steps:
          - checkout
          - run: gradle run -Dauto.url=parameters.auto_url -Dauto.token=parameters.auto_token -Dauto.file=${AUTO_FILE} -Dauto.dir=${AUTO_DIR} -Dauto.group=${AUTO_GROUP} -Dauto.wait=${AUTO_WAIT} -Dauto.score=${AUTO_SCORE}

workflows:
  tests:
    jobs:
      - circle-auto-v1/security-test
